server:
  port: 8082
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/student
    username: amigoscode
    password: amigoscode
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQL94Dialect
    format_sql: true
